pre-release-commit-message = "chore(release): prepare for"
tag-prefix = "v"
tag-message = "{{tag_name}}"
no-dev-version = true
consolidate-pushes = true
consolidate-commits = true
allow-branch = ["main"]
pre-release-replacements = [
	{ file="CHANGELOG.md", search="[unreleased]", replace="[{{version}}]" }
]
